version: "3.7"

services:
  webserver:
    build:
      args:
        - SERVICE_PATH=webserver
      context: .
      dockerfile: docker/go-webserver/Dockerfile
    volumes:
      - .:/app
    ports:
      - 9090:9090
    links:
      - mysql
    depends_on:
      - mysql

  # Database
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3310
    ports:
      - 3310:3310

networks:
  default:
    driver: bridge