root = "."
tmp_dir = "tmp"

[build]
  bin = "/tmp/webserver"
  cmd = "go build -o /tmp/webserver -v cmd/webserver/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = 500
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "webserver"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false