// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package mysql

import (
	"time"
)

type Transaction struct {
	ID              string
	Amount          int64
	TransactionType string
	TransactionDate time.Time
	Description     string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
